export const NEW_TASK_ITEM = "NEW_TASK_ITEM";
export const UPDATE_TASK_ITEM = "UPDATE_TASK_ITEM";
export const UPDATE_TASKS = "UPDATE_TASKS";
export const REMOVE_TASK = "REMOVE_TASK";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
